### ISSUE TITLE
Build error propagating from Tower

### ISSUE THREAD

**Issue by AliSajid** [JosephLenton/axum-test#104]
I am working on a project and it suddenly started failing. When checked, I traced it to `axum-test` crate and the `tower v5.0.0`. Could you please look into that?

The Tower community has a fix here: https://github.com/tower-rs/tower/issues/784
Thanks

**Comment by JosephLenton** [comment]
Hey, right now the current version of tower available is still `0.5.0`. The `Cargo.toml` in Axum Test is set to `0.5`, and should use `0.5.1` when available.

In the mean time please try a `cargo update`. You can also try locking a specific version of tower layer as `tower-layer = "=0.3.3"` in your Cargo toml.

If that still doesn't help, then would you be able to post your `Cargo.lock` and I can take a deeper look to see if something can be done.

**Comment by AliSajid** [comment]
Thank you. I guess I have to wait as well since this is a couple levels deep in my dependency tree. Thanks for everything. I appreciate the work on this.
