### ISSUE TITLE
Incompatibiliy between `axum_test::TestServer` and `tower_http::NormalizePathLayer`

### ISSUE THREAD

**Issue by agersant** [JosephLenton/axum-test#105]
I think it is not possible to instantiate a [TestServer](https://docs.rs/axum-test/latest/axum_test/struct.TestServer.html) that also applies path normalization (trailing slash trimming).

Prior discussion: https://github.com/tokio-rs/axum/discussions/2833

I tried this code:

```
let router = Router::new();
let app = NormalizePathLayer::trim_trailing_slash().layer(router);
let app = ServiceExt::<axum::extract::Request>::into_make_service(app);

let server = TestServer::new(app).unwrap();
```

but it fails to compile and I cannot see a way around it:

```
error[E0277]: the trait bound `axum::routing::IntoMakeService<tower_http::normalize_path::NormalizePath<axum::Router>>: axum_test::transport_layer::IntoTransportLayer` is not satisfied
 --> src\server\axum\test.rs:40:32
  |
40 |         let server = TestServer::new(app).unwrap();
  |                      --------------- ^^^ the trait `axum_test::transport_layer::IntoTransportLayer` is not implemented for `axum::routing::IntoMakeService<tower_http::normalize_path::NormalizePath<axum::Router>>`
  |                      |
  |                      required by a bound introduced by this call
  |
  = help: the trait `axum_test::transport_layer::IntoTransportLayer` is implemented for `axum::routing::IntoMakeService<axum::Router>
```

Thanks in advance!

**Comment by JosephLenton** [comment]
Hey @agersant , you should now find this fixed as a part of [15.7.0](https://crates.io/crates/axum-test/15.7.0). Let me know if there are any further issues!

**Comment by JosephLenton** [comment]
You should find an example of testing against a `NormalizePath<Router>` in the code here https://github.com/JosephLenton/axum-test/blob/b7f3ea3bd723970ed4a951e629cdf1ef5787492f/src/transport_layer/into_transport_layer/into_make_service.rs#L99-L116

**Comment by agersant** [comment]
Thank you so much!! ♥
