### ISSUE TITLE
How to send custom headers?

### ISSUE THREAD

**Issue by geekflyer** [JosephLenton/axum-test#12]
I may be missing something, but how can I add custom headers when sending a request? Seems like currently the headers vector is a private field and I can't find any method to set it.

**Comment by JosephLenton** [comment]
Hey @geekflyer , I have just released a new version 9.1.0. In that version you should find `add_header` which allows you to add headers to the `TestRequest`.

At the time I am writing this comment, the docs haven't built yet on docs.rs. But soon the docs should show up here https://docs.rs/axum-test/latest/axum_test/struct.TestRequest.html

(This is thanks to @ricerca1-itg)
