### ISSUE TITLE
Showing response body on panic?

### ISSUE THREAD

**Issue by jkaye2012** [JosephLenton/axum-test#123]
Hey there,

Thanks for the great library. Really enjoying it!

One small pain point has been `TestRequest::expect_success`. I like the convenience of this function, but the problem is that when it fails, you get a very generic message like this:

```
Expect status code within 2xx range, got 422 (Unprocessable Entity), for request PUT http://localhost/api/whatever
```

Whenever I see this, I always end up modifying my test to use `assert_text("")`, which will then show me something like:

```
assertion failed: `(left == right)`

Diff < left / right > :
>{"metadata":{"status":"Failure","reason":"Sorry, you violated a unique constraint!","timestamp":{"secs_since_epoch":1729860582,"nanos_since_epoch":389126565}},"body":null}
```

Is there any way to combine these two pieces of functionality? Ideally, whenever `expect_success` fails, I'd like to just see the response body (as text) printed to the console along with the response status.

Thanks!

**Comment by JosephLenton** [comment]
Hey @jkaye2012 , that is a great idea and I have ran into similar issues myself.

I'm working on a PR right now and should have it out over the next few days that will print the output within these assertions.

**Comment by jkaye2012** [comment]
Awesome  - let me know if I can help in any way!

**Comment by JosephLenton** [comment]
Hey @jkaye2012 , you should now find that change released as version [16.3.0](https://crates.io/crates/axum-test/16.3.0). Given the size of the change I've gone with a full bump just incase it's a surprise for people.

Please try it out and let me know if that works well for you. I've added pretty printing for Json responses which should help.

Enjoy!

**Comment by jkaye2012** [comment]
Looks great, thank you!

**Comment by JosephLenton** [comment]
No worries. Let me know if you have any more ideas!
