### ISSUE TITLE
HTTP transport layer hangs?

### ISSUE THREAD

**Issue by dnaaun** [JosephLenton/axum-test#126]
~I need to use the HTTP transport because I want to test websockets, but I think the HTTP transport layer truncates the body at around 10-11KB. Is that expected?~

I now have a new issue with the HTTP transport layer hanging, which I've outlined in [the comment below](https://github.com/JosephLenton/axum-test/issues/126#issuecomment-2540906679).

**Comment by JosephLenton** [comment]
Hey @dnaaun , no it isn’t expected.

Can you please provide more details, and if possible a code example of the issue.

**Comment by dnaaun** [comment]
Thanks for the quick reply Joseph! I tried to create a minimal repro, but the minimal repro didn't reproduce the problem 😂 .  Instead, I'm now having an issue where the HTTP transport simply hangs. I'll definitely report back if I get around to making a minimal repo. But if anyone wants to look into this with _a_ repro (tho not very minimal), 

1. The repo is at https://github.com/dnaaun/heimisch
2.  Running [this](https://github.com/dnaaun/heimisch/blob/559acf9ab8d392feac48e8d62218e0cf17b0e245/backend/src/tests/mod.rs#L302) test by running `cargo test --package backend -- hook --nocapture` shows the test is hanging.
3. One can be sure that the issue has to do with http transport because one can comment out [this line](https://github.com/dnaaun/heimisch/blob/559acf9ab8d392feac48e8d62218e0cf17b0e245/backend/src/tests/mod.rs#L167), and that same test invocation passes.

**Comment by JosephLenton** [comment]
Hey @dnaaun , I had a look today at this issue. On the topic of large payloads; I have just merged tests for WebSocket, Text Http requests, and Json Http requests, where I upload 16mb of data. Those tests have passed. I'm unable to replicate your issue.

On the topic of the tests hanging; I cannot see anything wrong with the Axum Test setup in your project. However I won't be able to run your project without rewriting large amounts of it. I'd be happy to help debug, however I'm afraid you will need to provide a more minimal example.

**Comment by dnaaun** [comment]
Merci, vielen dank, and thank you for looking into this!

> you will need to provide a more minimal example.

That's beyond fair. But I'm curious:

 > I won't be able to run your project without rewriting large amounts of it.
 
Thanks for letting me know!

**Comment by dnaaun** [comment]
Closing until I provide a more minimal repro.
