### ISSUE TITLE
Tests are extremely slow

### ISSUE THREAD

**Issue by bshankar** [JosephLenton/axum-test#127]
Thank you for such an ergonomic testing library. I'm really enjoying it. 🙂

I have a real world web app that uses SSE, axum-login and sqlite. 

All 30 tests written with axum-test take about `3 seconds` to run. They are simple API calls and page loads like login, logout etc.

I suspect this has to do with axum-test because if I test directly with axum and reqwest the tests finish in `0.05s`.

**Comment by JosephLenton** [comment]
Hey @bshankar , I took a look today and am unable to replicate your issue. You mentioned you have Axum Login + Sqlite. Could it be that most of the performance bottleneck is on the DB side?

If you could please provide a minimal example of your issue then I would be happy to take a look.

**Comment by bshankar** [comment]
Hi @JosephLenton 

I am using the mock server (default). I have also tried using the http test server. There was not much impact on performance. 
I am on Arch linux, Rust stable 1.83.0. 


> Hey @bshankar , I took a look today and am unable to replicate your issue. You mentioned you have Axum Login + Sqlite. Could it be that most of the performance bottleneck is on the DB side?
> 
> If you could please provide a minimal example of your issue then I would be happy to take a look.

I don't think the bottleneck is the DB because I ran the same tests with just `axum` and `reqwest`. They ran fast.

I will try to replicate it in a minimal example and post it soon.

**Comment by bshankar** [comment]
I rewrote all my tests again with just axum and reqwest and they were just as slow. I couldn't replicate the performance difference.

 I narrowed down the performance issue to `argon2` and `password_auth` crate. 
 https://github.com/RustCrypto/password-hashes/issues/104
 
 I am able to speed up the tests by enabling optimizations for argon2 crate in the dev build. Creating a test user cookie and reusing it has also helped a lot since signup and login are expensive.
 
Thank you again for this library. Closing.

**Comment by JosephLenton** [comment]
@bshankar I'm glad to hear you got to the bottom of it! I'm sorry I couldn't do more.

I'd be open to any random ideas you had which may have helped with tracking down the issue. Perhaps I could add something to axum-test for future users.

**Comment by bshankar** [comment]
@JosephLenton No worries. The issue wasn't even related to `axum-test`. It was my mistake to think it was related to axum-test. Sorry.

To track the issue, I just started from scratch and added each part of the API one by one until the tests got slower. Can't think of anything to add to axum-test at the moment. I don't know if this is worth mentioning in the docs or readme.
