### ISSUE TITLE
Unable to run tests on Windows machine

### ISSUE THREAD

**Issue by quanhua92** [JosephLenton/axum-test#4]
Hi,
I can't run the test on a Windows 10 machine. I have to switch to an Ubuntu WSL to run it.
Here is the message on the native terminal.

```   
Compiling backend v0.1.0 (C:\Users\quanh\workspace-c\GoViral\backend)
    Finished test [unoptimized + debuginfo] target(s) in 3.10s
     Running unittests src\main.rs (target\debug\deps\backend-da715d141979108d.exe)

running 1 test
test test_get_home::it_should_return_message ... FAILED

failures:

---- test_get_home::it_should_return_message stdout ----
thread 'test_get_home::it_should_return_message' panicked at 'Sending request failed: Expect Hyper Response to succeed on request to /

Caused by:
    0: error trying to connect: tcp connect error: The requested address is not valid in its context. (os error 10049)
    1: tcp connect error: The requested address is not valid in its context. (os error 10049)
    2: The requested address is not valid in its context. (os error 10049)', C:\Users\quanh\.cargo\registry\src\github.com-1ecc6299db9ec823\axum-test-7.2.0\src\test_request.rs:216:27
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    test_get_home::it_should_return_message

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.01s

error: test failed, to rerun pass `--bin backend`
```

**Comment by JosephLenton** [comment]
Thank you for raising this. I wrote this on MacOS and Linux.

I'll try and get a change to debug this on a Windows machine this week.

**Comment by JosephLenton** [comment]
This should now be resolved thanks to this PR https://github.com/JosephLenton/axum-test/pull/6, and this has been published as Version 8 https://crates.io/crates/axum-test/8.0.0 .

This was done by changing the default IP to use 127.0.0.1.

In case 127.0.0.1 isn't desirable, users can now pick the IP to use in the server configuration. This is a breaking change by removing the default socket address (which was IP + Port), and adding the means to set the IP or port to use independently of each other. This can be found in the `TestServerConfig`.
