### ISSUE TITLE
Support of multipart 

### ISSUE THREAD

**Issue by dimitri-correia** [JosephLenton/axum-test#51]
Unless I'm missing something, it's not yet possible to use multipart while testing.
As I use **axum = { version = "0.7.2", features = ["multipart"] }** and **async fn red_pixels(mut multipart: Multipart) -> (StatusCode, String) {}** in my code, I wanted to test that part.
I tried to use this crate like I would have with the reqwest  crate (where I need to set my cargo.toml to 
**reqwest = { version = "0.11.23", features = ["multipart"] }** )  but it doesn't seem to be possible here, and I didn't find something about that on the docs :

    #[tokio::test]
    async fn task2() {
        let app = get_day_11_router();

        // Run the application for testing.
        let server = TestServer::new(app).unwrap();

        // Send the request.
        let form = Form::new().part(
            "image",
            Part::bytes(include_bytes!("../../assets/decoration.png").as_slice())
                .file_name("decoration.png")
                .mime_str("image/png")
                .unwrap(),
        );
        let response = server.post("/red_pixels").multipart(form).await;

        response.assert_status(StatusCode::OK);
    }

do you plan to do something about it?
Thank you!

**Comment by JosephLenton** [comment]
Hey @dimitri-correia , I've just added multiform support in a new version. You should find it under version 14.2.0. I will be finishing the docs sometime in the future. The API is basically identical to the code sample you wrote.

 * TestRequest::multipart - https://docs.rs/axum-test/latest/axum_test/struct.TestRequest.html#method.multipart
 * Multipart form objects - https://docs.rs/axum-test/latest/axum_test/multipart/index.html

When you have some time please take a look and try it out. If there is anything missing or not right, let me know and I can take a look.

Have a lovely weekend!

**Comment by dimitri-correia** [comment]
Hey, thanks a ton for the quick help!
Just tested it out, and everything works like a charm for what I needed. Really appreciate your help!
Closing the issue.
Have a lovely weekend too!
