### ISSUE TITLE
No way to pass parameters that uses serde_qs

### ISSUE THREAD

**Issue by sam-rusty** [JosephLenton/axum-test#64]
Hi, first of all, i really appreciate the amount of effort you have put into improve the testing experience. GREAT JOB!

I am running into an issue, i believe i am missing something. 
In my my app i am using `serde_qs` to parse the query string in format `?filters[amount][op]=EQ&filters[amount][value]=[0]`, but i found no way in axum_test to pass query in such a format. 

Any suggestions?

**Comment by JosephLenton** [comment]
Hey, thanks for the support!

I have not used `serde_qs` myself. In the very short term you could try:
```rust
server.get("/my-api")
    .add_query_param("filters[filter][op]", "EQ")
    .await
    .assert_status_ok();
```
I'm not sure if the query params are being fully urlencoded in a way that messes with `serde_qs`. I'm also aware that's not great, but if it works, that should unblock you for the moment.

I am at RustNation tomorrow and Wednesday, and should have time then to look into proper support for this. I've not tried `serde_qs` myself, and will take a look at it. I will need to look before committing to what about to say, but I see no reason in principal why I can't add support for it behind a feature flag for you to enable.

**Comment by JosephLenton** [comment]
Hey @sam-rusty , in the last version `14.6.0` you should find `TestRequest::add_raw_query_param`. This bypasses the urlencoding. That should make your tests less painful in the immediate future, and drop the need to url decode server side.

I hope that helps! Please do let me know how well / not well it helps for you.

For the longer term I'm still mulling over how best to integrate this, as I'd like to avoid adding a query param function for each library out there. I have some ideas and will spend some time playing with them.

**Comment by sam-rusty** [comment]
Hey @JosephLenton thank you so much for your effort.

I am using latest version (14.6.0) but i am getting `no method named `add_raw_query_param` found for struct `axum_test::test_request::TestRequest` in the current scope` error. wondering if the crate was updated? 
Thanks!

**Comment by JosephLenton** [comment]
Hey @sam-rusty, I just tested on a project of mine and was able to find it under the `TestRequest`.

My message above may have been a bit misleading. The code to add the unsanitised query param is similar to adding a regular one ([docs here btw](https://docs.rs/axum-test/latest/axum_test/struct.TestRequest.html#method.add_raw_query_param)).

```rust
use ::axum::Router;
use ::axum_test::TestServer;

let app = Router::new();
let server = TestServer::new(app)?;

let response = server.get(&"/my-end-point")
    .add_raw_query_param(&"my-flag")
    .add_raw_query_param(&"array[]=123")
    .add_raw_query_param(&"filter[value]=some-value")
    .await;
```

If you still can't find the method. Then please ensuring the latest version is definitely being used locally. Either by setting the version to `axum-test = "=14.8"` in your Cargo.toml to force the latest version and no other, or taking a look inside your `Cargo.lock` file and search for `axum-test`. It will say which version is in use in there.

**Comment by sam-rusty** [comment]
Hey, i had to delete cargo.lock in order to get it working. thank you so much for your help, once again i love how simple axum-test is to use, great job! <3
