### ISSUE TITLE
Can `axum_test::TestServer` be Sync and Send?

### ISSUE THREAD

**Issue by Aditeya** [JosephLenton/axum-test#75]
I've tried adding a `TestServer` to  a `OnceCell<Arc<Mutex<TestServer>>>` but I get this error:

<details>
<summary>rust code</summary>

```rust
static SERVER_LOCAL: OnceCell<Arc<Mutex<TestServer>>> = OnceCell::const_new(); // tokio OnceCell but its same for OnceLock
async fn get_server_local() -> Arc<Mutex<TestServer>> {
    SERVER_LOCAL.get_or_init(|| async {
        let config = TestServerConfig::builder()
            .http_transport_with_ip_port(
                Some(IpAddr::V4(Ipv4Addr::new(0, 0, 0, 0))),
                Some(PORT),
            )
            .build();

        let app = get_app().layer(MockConnectInfo(SocketAddr::from(([127, 0, 0, 1], PORT))));

        Arc::new(Mutex::new(
                        TestServer::new_with_config(app, config)
                            .expect("Failed to create axum_test::TestServer"),
                    ))
    }).await.clone()
}
```

</details>

<details>
<summary>Error</summary>

```
error[E0277]: `(dyn TransportLayer + 'static)` cannot be sent between threads safely
   --> shepherd/src/server/api.rs:713:26
    |
713 |     static SERVER_LOCAL: OnceCell<Arc<Mutex<TestServer>>> = OnceCell::const_new();
    |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `(dyn TransportLayer + 'static)` cannot be sent between threads safely
    |
    = help: the trait `std::marker::Send` is not implemented for `(dyn TransportLayer + 'static)`, which is required by `tokio::sync::OnceCell<std::sync::Arc<std::sync::Mutex<TestServer>>>: std::marker::Sync`
    = note: required for `Unique<(dyn TransportLayer + 'static)>` to implement `std::marker::Send`
note: required because it appears within the type `Box<(dyn TransportLayer + 'static)>`
   --> /home/aditeya/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:197:12
    |
197 | pub struct Box<
    |            ^^^
    = note: required for `std::sync::Mutex<Box<(dyn TransportLayer + 'static)>>` to implement `std::marker::Sync`
    = note: 1 redundant requirement hidden
    = note: required for `std::sync::Arc<std::sync::Mutex<Box<(dyn TransportLayer + 'static)>>>` to implement `std::marker::Send`
note: required because it appears within the type `TestServer`
   --> /home/aditeya/.cargo/registry/src/index.crates.io-6f17d22bba15001f/axum-test-14.9.1/src/test_server.rs:65:12
    |
65  | pub struct TestServer {
    |            ^^^^^^^^^^
    = note: required for `std::sync::Mutex<TestServer>` to implement `std::marker::Sync`
    = note: 2 redundant requirements hidden
    = note: required for `tokio::sync::OnceCell<std::sync::Arc<std::sync::Mutex<TestServer>>>` to implement `std::marker::Sync`
    = note: shared static variables must have a type that implements `Sync`
```

</details>

If it can be Sync and Send then there wouldn't be a reason to use the `OnceLock<Arc<Mutex<T>>>`. However any help to get rid of the compilation error would be helpful as well.

**Comment by JosephLenton** [comment]
Hey @Aditeya , I have just make the `TransportLayer` sendable, which should unblock this. That is available in version [14.10.0](https://crates.io/crates/axum-test/14.10.0).

I believe the following code should now compile, allowing you to make this work:
```rust
static SERVER_LOCAL: OnceCell<TestServer> = OnceCell::const_new(); // tokio OnceCell but its same for OnceLock
async fn get_server_local() -> &TestServer {
    SERVER_LOCAL.get_or_init(|| async {
        let config = TestServerConfig::builder()
            .http_transport_with_ip_port(
                Some(IpAddr::V4(Ipv4Addr::new(0, 0, 0, 0))),
                Some(PORT),
            )
            .build();

        let app = get_app().layer(MockConnectInfo(SocketAddr::from(([127, 0, 0, 1], PORT))));

        TestServer::new_with_config(app, config)
                            .expect("Failed to create axum_test::TestServer")
    }).await
}
```

Separately, it looks like you are trying to share this server across multiple threads. I would take a step back and ask if that's really needed. I say that because you can have it start on a random port, and also use a mock network. Both should allow a per test server (although I don't know the wider context here so I could be wrong).

I'd be interested in what is pushing you to have one server shared like this, in case there is something I can do to make things simpler.

**Comment by Aditeya** [comment]
We have a web server  that runs on local machine and one of the requirements is that some endpoints cannot be exposed  to the LAN while  others can. We implemented an IP filter to Auth requests from LAN devices and localhost.

So I'm creating 2 servers:
- `MockConnectInfo` 0.0.0.0:1443 & TestSever 0.0.0.0:1443
- `MockConnectInfo` {machine_ip}:1444 & TestServer 0.0.0.0:1444

I just want to make requests from specific source IP ie `192.168.0.168` or `127.0.0.1`.  Ideally I would like to use one server to do all this. I suppose sharing the server across multiple threads isn't really required, I was just trying to avoid the overhead of rebuilding it.

**Comment by JosephLenton** [comment]
Okay, then yes that would make sense to do it that way.

If you do try building it on demand, that is not going to be a large cost. It will be quicker than you expect. It should be fine either way.

**Comment by Aditeya** [comment]
Yes, you're right it was faster than expected. Thank you!
