### ISSUE TITLE
Impl std::marker::Sync to use TestServer in tokio::sync::OnceCell

### ISSUE THREAD

**Issue by sam-rusty** [JosephLenton/axum-test#86]
I am trying to put `TestServer` in `OnceCell` to re-use in multiple test cases, but it doesn't let me do that because `std::marker::Sync`  is not implemented. This would be great to have to speed up thousands of tests i have that could re-use instead of spinning one server for each.

**Comment by JosephLenton** [comment]
Hey @sam-rusty , you should find `Sync` now added in [version 15.3.0](https://crates.io/crates/axum-test/15.3.0).

I'd also be interested in what the speedup looks like. Good luck!

**Comment by sam-rusty** [comment]
Thanks, very helpful as always <3. I will let you know for sure :)
